AppCRM/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppCRM.Models;

namespace AppCRM.Controllers
{
    public class ActividadesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public JsonResult Eventos(DateTime start, DateTime end)
        {
            var actividades = (from a in db.Actividades
                               join c in db.Clientes
                                    on a.ClienteId equals c.ClienteId
                               where a.FechaInicial >= start
                               && a.FechaFinal <= end
                               select new
                               {
                                   a.ActividadId,
                                   a.FechaInicial,
                                   c.Nombre,
                                   a.Descripcion
                               }).ToList();

            List<Events> eventos = new List<Events>();
            foreach(var item in actividades)
            {
                Events evento = new Events();
                evento.id = item.ActividadId;
                evento.start = item.FechaInicial.ToString("o");
                evento.end = item.FechaInicial.ToString("o");
                evento.title = item.Nombre + " " + item.Descripcion;
                eventos.Add(evento);
            }

            return Json(eventos, JsonRequestBehavior.AllowGet);

        }

        // GET: Actividades
        public ActionResult Index()
        {
            return View(db.Actividades.ToList());
        }

        // GET: Actividades/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Actividad actividad = db.Actividades.Find(id);
        //    if (actividad == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(actividad);
        //}

        // GET: Actividades/Create
        public ActionResult Create()
        {
            var tipos = new SelectList(db.TipoActividades.ToList(), "TipoActividadId", "Descripcion");
            ViewData["tipos"] = tipos;
            return PartialView();
        }

        // POST: Actividades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ActividadViewModel factividad)
        {
            Actividad actividad = new Actividad();
            if (ModelState.IsValid)
            {
                actividad.ActividadId = factividad.ActividadId;
                actividad.Descripcion = factividad.Descripcion;
                actividad.FechaInicial = factividad.FechaInicial;
                actividad.FechaFinal = factividad.FechaInicial;
                actividad.FechaInicialPlan = factividad.FechaInicial;
                actividad.FechaFinalPlan = factividad.FechaInicial;
                actividad.ClienteId = factividad.ClienteId;
                actividad.TipoActividadId = factividad.TipoActividadId;
                actividad.Estado = 0;
                db.Actividades.Add(actividad);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return Json(new { succes = true });
            }
            var tipos = new SelectList(db.TipoActividades.ToList(), "TipoActividadId", "Descripcion");
            ViewData["tipos"] = tipos;
            return PartialView(factividad);
        }

        // GET: Actividades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actividad actividad = db.Actividades.Find(id);
            if (actividad == null)
            {
                return HttpNotFound();
            }
            db.Entry(actividad).Reference("ClienteActividad").Load();
            ActividadViewModel factividad = new ActividadViewModel();
            factividad.ActividadId = actividad.ActividadId;
            factividad.Descripcion = actividad.Descripcion;
            factividad.FechaInicial = actividad.FechaInicial;
            factividad.ClienteId = actividad.ClienteId;
            factividad.TipoActividadId = actividad.TipoActividadId;
            factividad.nombre = actividad.ClienteActividad.Nombre;
            var tipos = new SelectList(db.TipoActividades.ToList(), "TipoActividadId", "Descripcion");
            ViewData["tipos"] = tipos;
            factividad.ObtenTelefonosYEmailsDeCliente();
            return PartialView(factividad);
        }

        // POST: Actividades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ActividadViewModel factividad)
        {
            
            if (ModelState.IsValid)
            {
                Actividad actividad = db.Actividades.Find(factividad.ActividadId);
                actividad.Descripcion = factividad.Descripcion;
                actividad.ActividadId = factividad.ActividadId;
                actividad.FechaInicial = factividad.FechaInicial;
                actividad.FechaFinal = factividad.FechaInicial;
                actividad.FechaInicialPlan = factividad.FechaInicial;
                actividad.FechaFinalPlan = factividad.FechaInicial;
                actividad.ClienteId = factividad.ClienteId;
                actividad.TipoActividadId = factividad.TipoActividadId;
                actividad.Estado = 0;
                db.Entry(actividad).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new {  success = true});
            }
            var tipos = new SelectList(db.TipoActividades.ToList(), "TipoActividadId", "Descripcion");
            ViewData["tipos"] = tipos;
            return PartialView(factividad);
        }

        // GET: Actividades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actividad actividad = db.Actividades.Find(id);
            if (actividad == null)
            {
                return HttpNotFound();
            }
            return View(actividad);
        }

        // POST: Actividades/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            Actividad actividad = db.Actividades.Find(id);
            db.Actividades.Remove(actividad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppCRM/Views/Actividades/Create.cshtml
@model AppCRM.Models.ActividadViewModel

@{
    ViewBag.Title = "Crear";
}



<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Nueva Actividad</h4>
        </div>
        <div class="modal-body">
            @using (Ajax.BeginForm("Create", "Actividades", null, new AjaxOptions
            {
                HttpMethod = "POST",
                Url = Url.Action("Create", "Actividades"),
                UpdateTargetId = "modal-content",
                OnSuccess = "closeModalCreate",
                InsertionMode = InsertionMode.Replace
            }, new { @class = "form-horizontal", role = "form", id = "frmCrear" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaInicial, new { htmlAttributes = new { @class = "form-control datepicker" } })
                            @Html.ValidationMessageFor(model => model.FechaInicial, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoActividadId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.TipoActividadId, ViewData["tipos"] as SelectList, "--SELECCIONE EL TIPO DE ACTIVIDAD", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TipoActividadId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ClienteId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ClienteId, new { htmlAttributes = new { @class = "form-control", id = "ClienteId" } })
                            @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Nombre del Cliente</label>
                        <div class="col-md-10">
                            @Html.TextBox("nombre", null, new { @class = "form-control" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


@*@Scripts.Render("~/bundles/jqueryval")*@
<script>
    $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        autoclose: true,
        language: 'es'
    });

    $('#nombre').autocomplete({
        source: '@Url.Action("Lista", "Clientes")',
        select: function (event, ui) {
            $('#ClienteId').val(ui.item.id);
            $('#nombre').val(ui.item.value);
            return false;
        }
    })
</script>

AppCRM/Views/Actividades/Delete.cshtml
@model AppCRM.Models.Actividad

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actividad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicialPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicialPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinalPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinalPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppCRM/Views/Actividades/Details.cshtml
@model AppCRM.Models.Actividad

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Actividad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicialPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicialPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinalPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinalPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ActividadId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppCRM/Views/Actividades/Edit.cshtml
@model AppCRM.Models.ActividadViewModel

@{
    ViewBag.Title = "Editar";
}
<div class="modal-dialog" role="document">
    <div class="modal-content" id="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">@ViewBag.Title</h4>
        </div>
        <div class="modal-body">
            @using (Ajax.BeginForm("Edit", "Actividades", null, new AjaxOptions
            {
                HttpMethod = "POST",
                Url = Url.Action("Edit", "Actividades"),
                UpdateTargetId = "modal-content",
                OnSuccess = "closeModalEdit",
                InsertionMode = InsertionMode.Replace
            }, new { @class = "form-horizontal", role = "form", id = "frmEditar" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ActividadId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.FechaInicial, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                            @Html.ValidationMessageFor(model => model.FechaInicial, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoActividadId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.TipoActividadId, ViewData["tipos"] as SelectList, "--SELECCIONE EL TIPO DE ACTIVIDAD", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TipoActividadId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ClienteId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ClienteId, new { htmlAttributes = new { @class = "form-control", id = "ClienteId" } })
                            @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Nombre del Cliente</label>
                        <div class="col-md-10">
                            @Html.TextBox("nombre", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Telefonos</label>
                        <div class="col-md-10">
                            <label style="color:blue;">@Model.Telefonos</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Correos</label>
                        <div class="col-md-10">
                            <label style="color:blue;">@Model.Emails</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Eliminar", "DeleteConfirmed", new { id=@Model.ActividadId }, new { @class="btn btn-danger" })
            </div>
        </div>
    </div>
</div>



@*<script>
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true,
            language: 'es'
        });
        $('#nombre').autocomplete({
            source: '@Url.Action("Lista", "Clientes")',
            select: function (event, ui) {
                $('#ClienteId').val(ui.item.id);
                $('#nombre').val(ui.item.value);
                return false;
            }
        })
    </script>*@

AppCRM/Views/Actividades/Index.cshtml
@model IEnumerable<AppCRM.Models.Actividad>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Crear Nuevo", "Create")*@
    <a class="btn btn-default" data-target="#modal-crear" data-toggle="modal" href="/Actividades/Create">Crear Nueva</a>
</p>

<div id="calendar"></div>

<div class="modal fade" id="modal-crear" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<div class="modal fade" id="modal-editar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>


@section Scripts{
    <script src="@Url.Content("~/Scripts/lib/moment.min.js")"></script>
    <script src="@Url.Content("~/Scripts/fullcalendar.js")"></script>
    <script src="@Url.Content("~/Scripts/locale/es.js")"></script>
    <script>
        function closeModalCreate(data) {
            if (data.succes) {
                $('#modal-crear').modal('hide');
                window.location.href = "/Actividades/index";
            }
        }

        function closeModalEdit(data) {
            $('#modal-editar').modal('hide');
            if (data.succes) {
                console.log("OK");
                $('#modal-editar').modal('hide');
                window.location.href = "/Actividades/index";
            } else {
                console.log("ERROR");
            }
        }

        function successFun(data, status) {
            $('#modal-editar').html(data);

            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                autoclose: true,
                language: 'es'
            });

            $('#nombre').autocomplete({
                source: '@Url.Action("Lista", "Clientes")',
                select: function (event, ui) {
                    $('#ClienteId').val(ui.item.id);
                    $('#nombre').val(ui.item.value);
                    return false;
                }
            });

            $('#modal-editar').modal('show');
        }


        $(document).ready(function () {
            $('#calendar').fullCalendar({
                events: '/Actividades/Eventos',
                eventClick: function (event, element) {
                    var serviceUrl = '/Actividades/Edit/' + event.id;
                    $.ajax({
                        type: "GET",
                        url: serviceUrl,
                        data: $(this).serialize(),
                        success: successFun

                    })
                }
            });
        })

        $("#modal-crear").draggable({
            handle: ".modal-header"
        });
    </script>
}