AppCRM/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AppCRM.Models
{
    public class Cliente
    {
        [Key]
        public int ClienteId { get; set; }

        public string Nombre { get; set; }

        public int TipoClienteId { get; set; }

        public TipoCliente Tipo { get; set; }

        public string RFC { get; set; }

        public Contacto ContactoCliente { get; set; }

        public string TipoPersonaSat { get; set; }

        public ICollection<Telefono> Telefonos { get; set; }

        public ICollection<Email> Correos { get; set; }

        public ICollection<Direccion> Direcciones { get; set; }
    }
}

AppCRM/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppCRM.Models;

namespace AppCRM.Controllers
{
    public class ClientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clientes
        public ActionResult Index()
        {
            BusquedaClienteModelView model = new BusquedaClienteModelView();
            return View(model);
        }

        public JsonResult Lista(string term)
        {
            ClientesViewModel cliente = new ClientesViewModel();
            return Json(cliente.ClientesAutocompletado(term), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuscaNombre(BusquedaClienteModelView model)
        {
            if (ModelState.IsValid)
            {
                ClientesViewModel clientes = new ClientesViewModel();
                clientes.BuscaPorNombre(model.NombreBuscar);
                return PartialView("_ListadoClientes", clientes.Clientes);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View("index", model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuscaEmail(BusquedaClienteModelView model)
        {
            if (ModelState.IsValid)
            {
                ClientesViewModel clientes = new ClientesViewModel();
                clientes.BuscaPorEmail(model.NombreBuscar);
                return PartialView("_ListadoClientes", clientes.Clientes);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("index", model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuscaTelefono(BusquedaClienteModelView model)
        {
            if (ModelState.IsValid)
            {
                ClientesViewModel clientes = new ClientesViewModel();
                clientes.BuscaPorTelefono(model.NombreBuscar);
                return PartialView("_ListadoClientes", clientes.Clientes);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("index", model);
            }
        }




        // GET: Clientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            db.Entry(cliente).Reference("Tipo").Load();
            db.Entry(cliente).Collection(p => p.Telefonos).Load();
            db.Entry(cliente).Collection(p => p.Correos).Load();
            db.Entry(cliente).Collection(p => p.Direcciones).Load();
            if (cliente == null)
            {
                return HttpNotFound();
            }
            
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            var list = new SelectList(new[]
                                          {
                                              new {ID="",Name="--SELECCIONE EL TIPO DE PERSONA"},
                                              new {ID="PERSONA FISICA",Name="PERSONA FISICA"},
                                              new{ID="PERSONA MORAL",Name="PERSONA MORAL"},
                                          },
               "ID", "Name", 1);
            var tipos = new SelectList(db.TipoClientes.ToList(), "TipoClienteId", "NombreTipo");
            ViewData["list"] = list;
            ViewData["tipos"] = tipos;

            return View();
        }

        // POST: Clientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Clientes.Add(cliente);
                db.SaveChanges();
                return Json(true);
            }

            return Json(false);
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            db.Entry(cliente).Collection(p => p.Telefonos).Load();
            db.Entry(cliente).Collection(p => p.Correos).Load();
            db.Entry(cliente).Collection(p => p.Direcciones).Load();
            //Cliente clienteMostrar = new Cliente();
            //clienteMostrar.ClienteId = cliente.ClienteId;
            //clienteMostrar.Nombre = cliente.Nombre;
            //clienteMostrar.TipoClienteId = cliente.TipoClienteId;
            //clienteMostrar.RFC = cliente.RFC;
            //clienteMostrar.TipoPersonaSat = cliente.TipoPersonaSat;

            //clienteMostrar.Telefonos = new List<Telefono>();
            //foreach (var item in clienteMostrar.Telefonos)
            //{
            //    Telefono tel = new Telefono();
            //    tel.TelefonoId = item.TelefonoId;
            //    tel.NumeroTelefonico = item.NumeroTelefonico;
            //    tel.Tipo = item.Tipo;
            //    tel.Principal = item.Principal;
            //    clienteMostrar.Telefonos.Add(tel);
            //}

            //clienteMostrar.Correos = new List<Email>();
            //foreach (var item in clienteMostrar.Correos)
            //{
            //    Email email = new Email();
            //    email.EmailId = item.EmailId;
            //    email.Principal = item.Principal;
            //    email.Direccion = item.Direccion;
            //    clienteMostrar.Correos.Add(email);
            //}

            //clienteMostrar.Direcciones = new List<Direccion>();
            //foreach(var item in clienteMostrar.Direcciones)
            //{
            //    Direccion dir = new Direccion();
            //    dir.DireccionId = item.DireccionId;
            //    dir.Calle = item.Calle;
            //    dir.NumExterior = item.NumExterior;
            //    dir.NumInterior = item.NumInterior;
            //    dir.Colonia = item.Colonia;
            //    dir.Municipio = item.Municipio;
            //    dir.Estado = item.Estado;
            //    clienteMostrar.Direcciones.Add(dir);
            //}

            var list = new SelectList(new[]
                                          {
                                              new {ID="",Name="--SELECCIONE EL TIPO DE PERSONA"},
                                              new {ID="PERSONA FISICA",Name="PERSONA FISICA"},
                                              new{ID="PERSONA MORAL",Name="PERSONA MORAL"},
                                          },
               "ID", "Name", 1);
            var tipos = new SelectList(db.TipoClientes.ToList(), "TipoClienteId", "NombreTipo");
            ViewData["list"] = list;
            ViewData["tipos"] = tipos;
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                Cliente clienteModificar = db.Clientes.Find(cliente.ClienteId);
                db.Entry(clienteModificar).Collection(p => p.Telefonos).Load();
                db.Entry(clienteModificar).Collection(p => p.Correos).Load();
                db.Entry(clienteModificar).Collection(p => p.Direcciones).Load();
                ProcesaTelefonos(cliente, clienteModificar);
                ProcesaEmails(cliente, clienteModificar);
                ProcesaDirecciones(cliente, clienteModificar); 
                clienteModificar.Nombre = cliente.Nombre;
                clienteModificar.TipoClienteId = cliente.TipoClienteId;
                clienteModificar.RFC = cliente.RFC;
                clienteModificar.TipoPersonaSat = cliente.TipoPersonaSat;
                db.Entry(clienteModificar).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true);
            }
            return Json(false);
        }

        private void ProcesaTelefonos(Cliente cliente, Cliente clienteModificar)
        {
            var telefonosExistentes = new List<Telefono>();
            if (clienteModificar.Telefonos != null)
                telefonosExistentes = clienteModificar.Telefonos.ToList<Telefono>();
            var telefonosModificados = new List<Telefono>();
            if (cliente.Telefonos != null)
                telefonosModificados = cliente.Telefonos.ToList<Telefono>();
            var telefonosAgregar = telefonosModificados.Except(telefonosExistentes);
            var telefonosEliminar = telefonosExistentes.Except(telefonosModificados);

            telefonosEliminar.ToList<Telefono>().ForEach(t => db.Entry(t).State = System.Data.Entity.EntityState.Deleted);

            foreach (Telefono telefono in telefonosAgregar)
            {
                clienteModificar.Telefonos.Add(telefono);
            }
        }

        private void ProcesaEmails(Cliente cliente, Cliente clienteModificar)
        {

AppCRM/Views/Clientes/Create.cshtml
@model AppCRM.Models.Cliente
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RFC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RFC, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TipoPersonaSat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoPersonaSat, ViewData["list"] as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPersonaSat, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TipoClienteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoClienteId, ViewData["tipos"] as SelectList,
                "--SELECCIONE EL TIPO DE CLIENTE", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoClienteId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                    Telefonos
                </a>
            </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
            <div class="panel-body">
                <form class="form-inline">
                    <div class="form-group">
                        <label for="Telefono">Telefono</label>
                        <input type="text" id="Telefono" class="form-control" />
                        <span class="error">El teléfono es requerido</span>
                    </div>
                    <div class="form-group">
                        <label for="Tipo">Tipo</label>
                        <input type="text" id="Tipo" class="form-control" />
                        <span class="error">El tipo es requerido</span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="TelPrincipal" value="1" class="form-control" /> Principal
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="button" id="add" value="agregar" class="btn btn-primary form-control" />
                    </div>
                </form>
                <br />
                <div id="telItems" class="container">
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                    Direcciones de correo electrónico
                </a>
            </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse">
            <div class="panel-body">
                <form class="form-inline">
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="text" id="Email" class="form-control" width="100" />
                        <span class="error">La dirección de correo electrónico es requerido</span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="EmailPrincipal" value="1" class="form-control"> Principal
                            </label>
                        </div>
                        <span class="error"></span>
                    </div>
                    <div class="form-group">
                        <input type="button" id="addEmail" value="agregar" class="btn btn-primary form-control" />
                    </div>
                </form>
                <br />
                <div id="emailItems" class="container">
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                    Direcciones
                </a>
            </h4>
        </div>
        <div id="collapse3" class="panel-collapse collapse">
            <div class="panel-body">
                <form class="form-inline">
                    <div class="form-group">
                        <label for="Calle">Calle</label>
                        <input type="text" id="Calle" class="form-control" width="100" />
                        <span class="error">La calle es requerida</span>
                    </div>
                    <div class="form-group">
                        <label for="NumExterior">Número exterior</label>
                        <input type="text" id="NumExterior" class="form-control" width="100" />
                        <span class="error">El número exterior es requerido</span>
                    </div>
                    <div class="form-group">
                        <label for="NumInterior">Número interior</label>
                        <input type="text" id="NumInterior" class="form-control" width="100" />
                        <span class="error"></span>
                    </div>
                    <div class="form-group">
                        <label for="Colonia">Colonia</label>
                        <input type="text" id="Colonia" class="form-control" width="100" />
                        <span class="error">La colonia es requerida</span>
                    </div>
                    <div class="form-group">
                        <label for="Municipio">Municipio</label>
                        <input type="text" id="Municipio" class="form-control" width="100" />
                        <span class="error">El municipio</span>
                    </div>
                    <div class="form-group">
                        <label for="Estado">Estado</label>
                        <input type="text" id="Estado" class="form-control" width="100" />
                        <span class="error">El Estado es requerido</span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="DirPrincipal" value="1" class="form-control"> Principal
                            </label>
                        </div>
                        <span class="error"></span>
                    </div>
                    <div class="form-group">
                        <input type="button" id="addDireccion" value="agregar" class="btn btn-primary form-control" />
                    </div>
                </form>
                <br />
                <div id="direccionesItems" class="container">
                </div>
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Crear" class="btn btn-primary" id="submit" />
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/Listas.js")"></script>
    <script src="@Url.Content("~/Scripts/FuncionesCliente.js")"></script>
    <script>
        $(document).ready(function () {
            $('#add').click(addTel_Click);
            $('#addEmail').click(addEmail_Click);
            $('#addDireccion').click(addDir_Click);
            $('#submit').click(crear_Click);
        });
    </script>
}

AppCRM/Views/Clientes/Delete.cshtml
@model AppCRM.Models.Cliente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tipo.NombreTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.NombreTipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RFC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RFC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPersonaSat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPersonaSat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo.NombreTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.NombreTipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppCRM/Views/Clientes/Details.cshtml
@model AppCRM.Models.Cliente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tipo.NombreTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.NombreTipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RFC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RFC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPersonaSat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPersonaSat)
        </dd>
    </dl>
</div>


<div>
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Telefonos
                </h4>
            </div>
            <div class="panel-body">
                <div id="telItems" class="container">
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Direcciones de correo electrónico
                </h4>
            </div>
            <div class="panel-body">
                <div id="emailItems" class="container">
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Direcciones
                </h4>
            </div>
            <div class="panel-body">
                <div id="direccionesItems" class="container"></div>
            </div>
        </div>
    </div>
</div>



<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClienteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/Listas.js")"></script>
    <script src="@Url.Content("~/Scripts/FuncionesCliente.js")"></script>
    <script>
        function LlenartelefonosDelModelo() {
            @foreach (var d in Model.Telefonos)
            {
                @:telItems.Agregar( @Html.Raw(Json.Encode(d)));
                                                            }
        }

        function LlenaremailsDelModelo() {
            @foreach (var d in Model.Correos)
            {
                @:emailItems.Agregar( @Html.Raw(Json.Encode(d)));
                                                            }
        }
        function LlenardireccionesDelModelo() {
            @foreach (var d in Model.Direcciones)
            {
                @:direccionesItems.Agregar( @Html.Raw(Json.Encode(d)));
                                                            }
        }

        $(document).ready(function () {
            LlenartelefonosDelModelo();
            LlenardireccionesDelModelo();
            LlenaremailsDelModelo();
            MostrarTelefonos(false);
            MostrarEmail(false);
            MostrarDirecciones(false);
        });
    </script>
}

AppCRM/Views/Clientes/Index.cshtml
@model AppCRM.Models.BusquedaClienteModelView
@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("Crear nuevo", "Create", null, new { @class = "btn btn-default" })
</p>
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>Búsqueda por nombre</h5>
            </div>
            <div class="panel-body">
                <div class="container">
                    @using (Ajax.BeginForm("BuscaNombre", "Clientes", null,
            new AjaxOptions
            {
                HttpMethod = "Post",
                UpdateTargetId = "ajaxtarget",
                LoadingElementId = "image_loading",
                InsertionMode = InsertionMode.Replace
            }, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "text-error" })
                        <div class="form-group">
                            @Html.LabelFor(t => t.NombreBuscar, new { @class = "control-label" })
                            @Html.TextBoxFor(t => t.NombreBuscar, new { @style = "width : 400px", @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-default" value="Buscar" />
                        </div>

                   
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>Búsqueda por dirección de correo electrónico</h5>
            </div>
            <div class="panel-body">
                <div class="container">
                    @using (Ajax.BeginForm("BuscaEmail", "Clientes", null,
            new AjaxOptions
            {
                HttpMethod = "Post",
                UpdateTargetId = "ajaxtarget",
                LoadingElementId = "image_loading",
                InsertionMode = InsertionMode.Replace
            }, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "text-error" })
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            @Html.TextBoxFor(t => t.NombreBuscar, new { @style = "width : 300px", @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-default" value="Buscar" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>Búsqueda por número telefónico</h5>
            </div>
            <div class="panel-body">
                <div class="container">
                    @using (Ajax.BeginForm("BuscaTelefono", "Clientes", null,
            new AjaxOptions
            {
                HttpMethod = "Post",
                UpdateTargetId = "ajaxtarget",
                LoadingElementId = "image_loading",
                InsertionMode = InsertionMode.Replace
            }, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "text-error" })
                        <div class="form-group">
                            <label class="control-label">Telefono</label>
                            @Html.TextBoxFor(t => t.NombreBuscar, new { @style = "width : 400px", @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-default" value="Buscar" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <img class="loadercentrado" id="image_loading" src="~/imgs/loading.gif" width="30" height="30" style="display:none" />
</div>
<div id="ajaxtarget"></div>

AppCRM/Views/Clientes/_ListadoClientes.cshtml
@model IEnumerable<AppCRM.Models.ClientesBusqueda>
@{
    ViewBag.Title = "_ListadoClientes";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RFC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoPersonaSat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RFC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoPersonaSat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ClienteId }) |
                @Html.ActionLink("Detalle", "Details", new { id = item.ClienteId }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.ClienteId })
            </td>
        </tr>
    }

</table>